//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string City { get; set; }
        public string Age { get; set; }
        public long Phone { get; set; }
        public int Pincode { get; set; }
    }
}
